"""Create a baseline migrations

Revision ID: 046b97f35460
Revises: 5b632c83b60f
Create Date: 2023-09-08 10:50:18.972553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '046b97f35460'
down_revision = '5b632c83b60f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
