"""Create a baseline migrations

Revision ID: 07a0afab8c28
Revises: a34c4fb6594f
Create Date: 2023-09-08 12:23:58.551960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07a0afab8c28'
down_revision = 'a34c4fb6594f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
