"""Create a baseline migrations

Revision ID: 3ea6d062b621
Revises: 07a0afab8c28
Create Date: 2023-09-08 12:55:18.318043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ea6d062b621'
down_revision = '07a0afab8c28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
