"""se agregaron campos surname, date birth y nickname a la tabla de users

Revision ID: 615fe8e22fd8
Revises: 670a2eadeed0
Create Date: 2023-09-10 20:59:29.794692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '615fe8e22fd8'
down_revision = '670a2eadeed0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('surname', sa.String(length=50), nullable=False))
    op.add_column('users', sa.Column('name', sa.String(length=50), nullable=False))
    op.add_column('users', sa.Column('password', sa.String(length=50), nullable=False))
    op.add_column('users', sa.Column('email', sa.String(length=100), nullable=False))
    op.add_column('users', sa.Column('date_of_birth', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'date_of_birth')
    op.drop_column('users', 'email')
    op.drop_column('users', 'password')
    op.drop_column('users', 'name')
    op.drop_column('users', 'surname')
    # ### end Alembic commands ###
