"""Create a baseline migrations

Revision ID: 957c604c6530
Revises: d35d866b3da4
Create Date: 2023-09-08 11:05:35.679078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '957c604c6530'
down_revision = 'd35d866b3da4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
