"""Create a baseline migrations

Revision ID: a34c4fb6594f
Revises: 957c604c6530
Create Date: 2023-09-08 11:08:40.509941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a34c4fb6594f'
down_revision = '957c604c6530'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
