"""Create a baseline migrations

Revision ID: d35d866b3da4
Revises: 6ddd75e26688
Create Date: 2023-09-08 10:59:58.261665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd35d866b3da4'
down_revision = '6ddd75e26688'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
